# -*- coding: utf-8 -*-
"""Day2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fbq1ZlrTEXvN7AXzqIr_ay4_Ls-2Jux_

#Section 1
"""

print("This is my second class on AI")

"""Function in Python"""

def area_of_square (num):
  return num*num
print("the area is:",area_of_square(6))
print("the area of seond square is:", area_of_square(16))

"""def area_of_circle(num):
  return num*num
print("the area is:"

List in Python
"""

# Creating a list of fruits
fruits = ["apple", "banana", "Kiwi", "orange", "strewary"]
# Accessing elements
# print(fruits[0]) accessing first elements in the list
# print(fruits[4]) accessing 5th elements in the list.

# adding elements from list
fruits.append("mango")
print(fruits)

# Removing elements from list
fruits.remove("Kiwi")
print(fruits)

"""#**Tuples in Python**"""

#**Dictionaries in Python**

# Creating a Dictionary
student={
  "name": "Ram Prasai",
  "age" : 30,
  "Course" : "Computer Science"}
#Accessing alues of a particular key in a dictionary
print(student["age"])
student["age"]=55
print(student["age"])

print(student["address"])
student["address"]="Kathmandu"
print(student["address"])

num=int(input("what is the temperature c"))
def todays_temp(num):
  return num*9/5+32
print("the temperature in fahrenhit is:",todays_temp(num))

"""String Manipulation in Python(Tomorrow)"""

num=int(input("what is the temperature f"))
def todays_temp(num):
  return (num-32)*5/9
print("the temperature in celcius is:",todays_temp(num))

